from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(865, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.trainInput = QtWidgets.QLineEdit(self.centralwidget)
        self.trainInput.setObjectName("trainInput")
        self.gridLayout.addWidget(self.trainInput, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.funcOutput = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.funcOutput.setFont(font)
        self.funcOutput.setAutoFillBackground(False)
        self.funcOutput.setText("")
        self.funcOutput.setScaledContents(False)
        self.funcOutput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.funcOutput.setObjectName("funcOutput")
        self.gridLayout.addWidget(self.funcOutput, 4, 0, 1, 1)
        self.trainButton = QtWidgets.QPushButton(self.centralwidget)
        self.trainButton.setObjectName("trainButton")
        self.gridLayout.addWidget(self.trainButton, 3, 0, 1, 3)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.confMat = QtWidgets.QLabel(self.centralwidget)
        self.confMat.setText("")
        self.confMat.setObjectName("label_3")
        self.confMat.setScaledContents(True)
        self.gridLayout.addWidget(self.confMat, 4, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Enter the percentage of train data:"))
        self.label_2.setText(_translate("MainWindow", "Select the algorithm to train data:"))
        self.trainButton.setText(_translate("MainWindow", "Apply"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Support Vector Classifier"))
        self.comboBox.setItemText(2, _translate("MainWindow", "K Nearest Neighbors"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Random Forest"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Decision Tree"))
        self.comboBox.setItemText(5, _translate("MainWindow", "XGBoost"))
